import { isNative, isIOS, STORE_URLS } from '@js/platform.js'

/**
 * What "update now" should actually do.
 *
 * On the web, reloading fetches the new service worker and its precache, which
 * is genuinely how a PWA updates.
 *
 * In a shipped binary a reload re-runs the same bundled app forever. The new
 * version is in the store, so that is where the button has to go. Getting this
 * wrong produces the worst kind of bug report — "I pressed update and nothing
 * happened", repeatedly, with nothing in any log.
 */
export function updateTarget({ native = isNative, ios = isIOS } = {}) {
  if (!native) return { kind: 'reload' }
  return { kind: 'store', url: ios ? STORE_URLS.ios : STORE_URLS.android }
}

/**
 * Let a waiting service worker take over.
 *
 * A reload alone does not do it. A new worker installs and then waits until
 * no client is controlled by the old one, and reloading a tab keeps that
 * client alive — so the old precache keeps being served until every tab and
 * installed instance is closed. That is why a deploy can be live on the
 * server and invisible on the device for days.
 *
 * The worker generated by workbox listens for a SKIP_WAITING message, so the
 * update button can say the word. Nothing happens until someone presses it,
 * which is the point: no assets swapped under a page mid-session.
 */
export async function activateWaitingWorker(deps = {}) {
  const { nav = typeof navigator === 'undefined' ? null : navigator } = deps
  if (!nav || !('serviceWorker' in nav)) return false

  const registration = await nav.serviceWorker.getRegistration().catch(() => null)
  if (!registration) return false

  // Ask for the newest worker before looking: a long-running session may not
  // have checked since the deploy.
  await registration.update().catch(() => {})
  if (!registration.waiting) return false

  const tookOver = new Promise((resolve) => {
    nav.serviceWorker.addEventListener('controllerchange', resolve, { once: true })
    // Never hang the button on a worker that does not answer.
    setTimeout(resolve, 3000)
  })

  registration.waiting.postMessage({ type: 'SKIP_WAITING' })
  await tookOver

  return true
}

/** Perform it. Split from updateTarget so the decision is testable on its own. */
export async function performUpdate(deps = {}) {
  const {
    target = updateTarget(),
    reload = () => window.location.reload(),
    open = (url) => window.open(url, '_system'),
    activate = activateWaitingWorker,
  } = deps

  if (target.kind === 'reload') {
    // Hand over first, then reload — reloading before the new worker controls
    // the page just re-serves the old precache and the button appears broken.
    await activate(deps)
    reload()

    return target
  }

  open(target.url)

  return target
}
